title: "P. Kerfriden | Computational Mechanics & AI"
description: "Research, teaching, and thoughts on nonlinear mechanics, simulation, and machine learning in engineering."

theme: jekyll-theme-minimal

baseurl: ""      
url: "https://kerfriden.github.io"  
