title: "Computational Mechanics & AI"
description: "Material Modelling, Probabilistic Numerics & Machine Learning"

theme: jekyll-theme-minimal

baseurl: ""      
url: "https://kerfriden.github.io"  
