title: "Mechanics of Materials and Artifical Intelligence"
description: "A research blog about Computational Mechanics, Probabilistic Numerics & Machine Learning"

theme: jekyll-theme-minimal

baseurl: "" 
url: "https://kerfriden.github.io"  
