title: "Computational Mechanics & AI"
description: "A research blog about Material Modelling, Probabilistic Numerical Methods & Machine Learning"

theme: jekyll-theme-minimal

baseurl: "" 
url: "https://kerfriden.github.io"  
