title: "Research Blog"
description: "Computational Mechanics & Material Modelling, Probabilistic Numerics & Machine Learning"

theme: jekyll-theme-minimal

baseurl: ""      
url: "https://kerfriden.github.io"  
