title: "P. Kerfriden | Computational Mechanics & AI"
description: "Research, teaching, and thoughts on nonlinear mechanics, simulation, and machine learning in engineering."

url: "https://kerfriden.github.io"
baseurl: "/blog" # because your repo is https://kerfriden.github.io/blog/

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

author:
  name: "Pierre Kerfriden"
  avatar: "/assets/images/logo.png"
  bio: "Researcher."

# Optional: display navigation
show_nav: true
