title: P. Kerfriden | Computational Mechanics & AI
description: Research, teaching, and thoughts on nonlinear mechanics, simulation, and machine learning in engineering.
#theme: jekyll-theme-minimal
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
baseurl: "/blog"
url: "https://username.github.io"
#logo: /assets/images/logo.png

# Author (optional, useful for author profiles)
author:
  name: "Pierre Kerfriden"
  avatar: "/assets/images/logo.png"   # Put your avatar in assets/images
  bio: "Researcher."

# Navigation (customize menu links)
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Teaching
    url: /teaching/
  - title: Contact
    url: /contact/

# Social links (optional)
social:
  linkedin: kerfriden
