title: "P. Kerfriden | Computational Mechanics & AI"
description: "Research, teaching, and thoughts on nonlinear mechanics, simulation, and machine learning in engineering."

theme: jekyll-minimal

baseurl: ""       # if your site is user.github.io, baseurl should be empty
url: "https://kerfriden.github.io"  # your actual URL
