title: P. Kerfriden | Computational Mechanics & AI
description: Research, teaching, and thoughts on nonlinear mechanics, simulation, and machine learning in engineering.
theme: jekyll-theme-minimal
baseurl: "/blog"
logo: /assets/images/logo.png
